### sign up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "spam@bar.de",
    "password": "topSecret",
    "id": 1
}

### loggin 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "foo@bar.de",
    "password": "topSecret",
    "id": 1
}